### ISSUE TITLE
Unified mode - tool changes when adding labels

### ISSUE THREAD

**Issue by dobkeratops** [ImageMonkey/imagemonkey-core#263]
Not sure why but in unified mode, usually when you enter a label the tool will switch to select (and sometimes rectangular annotation)
One guess is that it’s picking up hotkeys while you type and changing..

.. and indeed I just confirmed that’s what it is doing (r rectangle , s select)

I noticed it a bit more on the iPad where you have to scroll back up to click the tool again.

I guess it’s down to how the UI routes keypresses .. can it suppress keypresses for hotkeys whilst a text entry dialogue is open? A brute force fix would be to remember the tool when you start entering a label and deselect it .. but a real fix would prevent other unforeseen events from future hotkeys.

It’s also less of an issue if you enter a few labels together then annotated them

Overall a low priority issue ( search unlabelled for unified and optimising screen layout for work area are more important IMO.. without the toolbar being scrolled off so often you’ll see what tool is activated )

**Comment by bbernhard** [comment]
should be fixed now :)
