### ISSUE TITLE
SSL certificate or something 

### ISSUE THREAD

**Issue by dobkeratops** [ImageMonkey/imagemonkey-core#310]
hi, 
seems something is up with the site.. not entirely familiar with this sort of thing myself but i'm guessing this is something that would need to be refreshed ..
.. will you be keeping this site up into the future ?
hopefully if you do wind it down it'll be possible to share the data accumulated in it in an accessible form.

.. but I hope you will keep it going. multi-modal AI models are the future , and there's all the controversy over data-scraping & IP .. the kind of open-source labelling we're doing here should still be useful 

![Screenshot 2024-03-01 at 08 51 13](https://github.com/ImageMonkey/imagemonkey-core/assets/1120754/367611be-24a0-45e7-8bd6-36929c04e65a)

**Comment by bbernhard** [comment]
Sorry, completely forgot to renew the certificate! Should be fixed now. 

If Hetzner does not increase the costs (I am currently paying ~90 Euro per month), I hope that I can continue to keep the service running. Of course I can't promise anything, but I'll do my best :). If I ever need to shut it down, I'll try to ping you in advance and create a full copy of the data.

Unfortunately I do not have much time to do some feature development, so it is mostly in maintenance mode. So, keeping the service up to date, installing security fixes, etc. 

At the moment I am going through all the images that aren't unlocked yet and unlock them. In the past few weeks I unlocked ~15k images, ~16k images still to go.

**Comment by dobkeratops** [comment]
awesome, yeah I can see it again,thanks
